apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: school-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
